framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        #prefix_seed: your_vendor_name/app_name

        # The "app" cache stores to the filesystem by default.
        # The data in this cache should persist between deploys.
        app: cache.adapter.redis
        default_redis_provider: '%env(LOCK_DSN)%'
        #app: cache.adapter.apcu

        # Namespaced pools use the above "app" backend by default
        pools:
            app.job_sync_scheduler_cache:
                adapter: cache.adapter.redis
                provider: '%env(LOCK_DSN)%'

when@test:
    framework:
        cache:
            pools:
                app.job_sync_scheduler_cache:
                    adapter: cache.adapter.array
                    provider: null
