<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260821140000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create candidate profiles, skills, candidate skills and CV documents.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE candidate_profile (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(160) DEFAULT NULL, location VARCHAR(160) DEFAULT NULL, minimum_salary INT DEFAULT NULL, preferred_contract_types JSON NOT NULL, preferred_remote_policy VARCHAR(255) NOT NULL, years_of_experience INT DEFAULT NULL, raw_cv_text TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN candidate_profile.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN candidate_profile.updated_at IS \'(DC2Type:datetime_immutable)\'');

        $this->addSql('CREATE TABLE skill (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, normalized_name VARCHAR(120) NOT NULL, category VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_skill_normalized_name ON skill (normalized_name)');

        $this->addSql('CREATE TABLE candidate_skill (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, candidate_profile_id INT NOT NULL, skill_id INT NOT NULL, level VARCHAR(255) DEFAULT NULL, years_of_experience INT DEFAULT NULL, is_core_skill BOOLEAN NOT NULL, confidence DOUBLE PRECISION DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_CANDIDATE_SKILL_PROFILE ON candidate_skill (candidate_profile_id)');
        $this->addSql('CREATE INDEX IDX_CANDIDATE_SKILL_SKILL ON candidate_skill (skill_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_candidate_skill ON candidate_skill (candidate_profile_id, skill_id)');
        $this->addSql('ALTER TABLE candidate_skill ADD CONSTRAINT FK_CANDIDATE_SKILL_PROFILE FOREIGN KEY (candidate_profile_id) REFERENCES candidate_profile (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE candidate_skill ADD CONSTRAINT FK_CANDIDATE_SKILL_SKILL FOREIGN KEY (skill_id) REFERENCES skill (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE cv_document (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, candidate_profile_id INT NOT NULL, original_filename VARCHAR(255) NOT NULL, stored_filename VARCHAR(255) NOT NULL, mime_type VARCHAR(100) NOT NULL, size INT NOT NULL, sha256 VARCHAR(64) NOT NULL, status VARCHAR(255) NOT NULL, extracted_text TEXT DEFAULT NULL, analysis_result JSON DEFAULT NULL, error_message TEXT DEFAULT NULL, analyzer VARCHAR(80) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, analyzed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_CV_DOCUMENT_PROFILE ON cv_document (candidate_profile_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CV_DOCUMENT_STORED_FILENAME ON cv_document (stored_filename)');
        $this->addSql('CREATE UNIQUE INDEX uniq_profile_cv_hash ON cv_document (candidate_profile_id, sha256)');
        $this->addSql('COMMENT ON COLUMN cv_document.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN cv_document.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN cv_document.analyzed_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE cv_document ADD CONSTRAINT FK_CV_DOCUMENT_PROFILE FOREIGN KEY (candidate_profile_id) REFERENCES candidate_profile (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE cv_document');
        $this->addSql('DROP TABLE candidate_skill');
        $this->addSql('DROP TABLE skill');
        $this->addSql('DROP TABLE candidate_profile');
    }
}
