<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260822120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add the single owner account used by password and Google authentication.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE app_account (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, password VARCHAR(255) DEFAULT NULL, google_subject VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_ACCOUNT_EMAIL ON app_account (email)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_ACCOUNT_GOOGLE_SUBJECT ON app_account (google_subject)');
        $this->addSql("COMMENT ON COLUMN app_account.created_at IS '(DC2Type:datetime_immutable)'");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE app_account');
    }
}
