<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260821193000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create deterministic compatibility scores between candidate profiles and job offers.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE job_match (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, global_score INT NOT NULL, hard_criteria_score INT NOT NULL, semantic_score INT DEFAULT NULL, stack_score INT NOT NULL, experience_score INT NOT NULL, salary_score INT NOT NULL, location_score INT NOT NULL, contract_score INT NOT NULL, remote_score INT NOT NULL, backend_score INT NOT NULL, explanation JSON NOT NULL, analyzed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, candidate_profile_id INT NOT NULL, job_offer_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7B077875FE3D0586 ON job_match (candidate_profile_id)');
        $this->addSql('CREATE INDEX IDX_7B0778753481D195 ON job_match (job_offer_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_job_match_candidate_offer ON job_match (candidate_profile_id, job_offer_id)');
        $this->addSql('ALTER TABLE job_match ADD CONSTRAINT FK_7B077875FE3D0586 FOREIGN KEY (candidate_profile_id) REFERENCES candidate_profile (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE job_match ADD CONSTRAINT FK_7B0778753481D195 FOREIGN KEY (job_offer_id) REFERENCES job_offer (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE job_match DROP CONSTRAINT FK_7B077875FE3D0586');
        $this->addSql('ALTER TABLE job_match DROP CONSTRAINT FK_7B0778753481D195');
        $this->addSql('DROP TABLE job_match');
    }
}
