<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260824100000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add roles to app_account, create scheduler_execution_log and messenger_messages tables.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("ALTER TABLE app_account ADD roles JSON NOT NULL DEFAULT '[]'");
        $this->addSql('ALTER TABLE app_account ALTER roles DROP DEFAULT');
        $this->addSql('CREATE TABLE scheduler_execution_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, schedule_name VARCHAR(100) NOT NULL, command_or_message VARCHAR(255) NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, finished_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, duration_ms INT DEFAULT NULL, status VARCHAR(255) NOT NULL, processed_count INT NOT NULL, details TEXT DEFAULT NULL, error_message TEXT DEFAULT NULL, triggered_by VARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_scheduler_exec_started_at ON scheduler_execution_log (started_at)');
        $this->addSql('CREATE INDEX idx_scheduler_exec_schedule_name ON scheduler_execution_log (schedule_name)');
        $this->addSql('CREATE INDEX idx_scheduler_exec_status ON scheduler_execution_log (status)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('DROP TABLE scheduler_execution_log');
        $this->addSql('ALTER TABLE app_account DROP roles');
    }
}
