<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260821185206 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create job sources and normalized job offers.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE job_offer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, external_id VARCHAR(120) NOT NULL, url TEXT NOT NULL, title VARCHAR(255) NOT NULL, company VARCHAR(255) DEFAULT NULL, location VARCHAR(255) DEFAULT NULL, contract_type VARCHAR(80) DEFAULT NULL, minimum_salary INT DEFAULT NULL, maximum_salary INT DEFAULT NULL, remote_policy VARCHAR(80) DEFAULT NULL, years_of_experience INT DEFAULT NULL, description TEXT DEFAULT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, valid_through TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, first_seen_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_seen_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(255) NOT NULL, raw_payload JSON NOT NULL, content_hash VARCHAR(64) NOT NULL, source_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_288A3A4E953C1C61 ON job_offer (source_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_job_offer_source_external ON job_offer (source_id, external_id)');
        $this->addSql('CREATE TABLE job_source (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, url TEXT NOT NULL, provider VARCHAR(255) NOT NULL, enabled BOOLEAN NOT NULL, last_sync_started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_success_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_error TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE job_offer ADD CONSTRAINT FK_288A3A4E953C1C61 FOREIGN KEY (source_id) REFERENCES job_source (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE job_offer DROP CONSTRAINT FK_288A3A4E953C1C61');
        $this->addSql('DROP TABLE job_offer');
        $this->addSql('DROP TABLE job_source');
    }
}
